#!/usr/bin/env python3

"""
tabulate_cross_section.py

Generate a cross section table file for the SPARTA "collide table" style.

Two modes:

  vss   emit the analytic VHS/VSS total cross section for a species pair,
        read from a SPARTA species file and VSS parameter file.  Useful for
        verification: "collide table" with such a table must reproduce
        "collide vss" to within the interpolation error.

  csv   convert a two-column file of (x, sigma) values, e.g. published or
        computed cross section data, into the table format.

Examples:

  tabulate_cross_section.py vss --species data/ar.species --vss data/ar.vss \\
      --pair Ar Ar --emin 1.0e-4 --emax 1.0e3 -n 200 \\
      --keyword AR_AR_VHS -o data/ar_ar.tab

  tabulate_cross_section.py csv mydata.csv --keyword N2_N2_ELASTIC \\
      --xunits eV --yunits A^2 -o n2_n2.tab

See doc/collide.html for the table file format.
"""

import argparse
import math
import sys

BOLTZ = 1.380649e-23
EV2J = 1.602176634e-19

XUNIT_SCALE = {"eV": EV2J, "J": 1.0, "K": BOLTZ, "m/s": 1.0}
YUNIT_SCALE = {"m^2": 1.0, "cm^2": 1.0e-4, "A^2": 1.0e-20}


def read_species(fname):
    """Return {id: mass} from a SPARTA species file."""
    species = {}
    with open(fname) as fp:
        for line in fp:
            line = line.split("#")[0].strip()
            if not line:
                continue
            words = line.split()
            if len(words) < 3:
                continue
            species[words[0]] = float(words[2])
    return species


def read_vss(fname, isp, jsp):
    """Return (diam, omega, tref) for the isp/jsp pair from a VSS param file.

    An explicit cross-species line wins; otherwise the two self lines are
    averaged, exactly as CollideVSS::read_param_file() does.
    """
    self_params = {}
    cross = None
    with open(fname) as fp:
        for line in fp:
            line = line.split("#")[0].strip()
            if not line:
                continue
            words = line.split()
            if len(words) >= 5 and words[2] == "table":
                continue
            try:
                float(words[1])
                is_self = True
            except ValueError:
                is_self = False
            if is_self:
                if len(words) < 5:
                    continue
                self_params[words[0]] = tuple(float(w) for w in words[1:4])
            else:
                if len(words) < 6:
                    continue
                if {words[0], words[1]} == {isp, jsp}:
                    cross = tuple(float(w) for w in words[2:5])

    if cross:
        return cross
    for name in (isp, jsp):
        if name not in self_params:
            sys.exit("error: species %s not found in %s" % (name, fname))
    a = self_params[isp]
    b = self_params[jsp]
    return tuple(0.5 * (a[k] + b[k]) for k in range(3))


def vss_sigma(g, diam, omega, tref, mr):
    """VHS/VSS total cross section at relative speed g, in m^2.

    Matches CollideVSS: sigma*g = prefactor * (g^2)^(1-omega) with
    prefactor = pi*d^2 * (2*k*Tref/mr)^(omega-1/2) / Gamma(5/2-omega).
    """
    prefactor = (math.pi * diam * diam *
                 (2.0 * BOLTZ * tref / mr) ** (omega - 0.5) /
                 math.gamma(2.5 - omega))
    return prefactor * g ** (1.0 - 2.0 * omega)


def write_table(fp, keyword, xs, sigmas, xvar, xunits, yunits, extrap, header):
    for line in header:
        fp.write("# %s\n" % line)
    fp.write("\n%s\n" % keyword)
    fp.write("N %d X %s XUNITS %s YUNITS %s EXTRAP %s %s\n\n" %
             (len(xs), xvar, xunits, yunits, extrap[0], extrap[1]))
    for i, (x, s) in enumerate(zip(xs, sigmas)):
        fp.write("%-6d %- 20.12g %- 20.12g\n" % (i + 1, x, s))


def grid(lo, hi, n, logspace):
    if n < 2:
        sys.exit("error: need at least 2 points")
    if logspace:
        if lo <= 0.0:
            sys.exit("error: log spacing requires a positive lower bound")
        step = math.log(hi / lo) / (n - 1)
        return [lo * math.exp(i * step) for i in range(n)]
    step = (hi - lo) / (n - 1)
    return [lo + i * step for i in range(n)]


def cmd_vss(args):
    species = read_species(args.species)
    isp, jsp = args.pair
    for name in (isp, jsp):
        if name not in species:
            sys.exit("error: species %s not found in %s" % (name, args.species))
    mi, mj = species[isp], species[jsp]
    mr = mi / 2.0 if isp == jsp else mi * mj / (mi + mj)

    diam, omega, tref = read_vss(args.vss, isp, jsp)

    xs = grid(args.emin, args.emax, args.n, not args.linear)
    sigmas = []
    for e in xs:
        g = math.sqrt(2.0 * e * EV2J / mr)
        sigmas.append(vss_sigma(g, diam, omega, tref, mr) / YUNIT_SCALE[args.yunits])

    header = [
        "VHS/VSS total cross section for %s + %s" % (isp, jsp),
        "generated by tools/tabulate_cross_section.py from %s" % args.vss,
        "diam = %g m, omega = %g, Tref = %g K, m_r = %g kg" %
        (diam, omega, tref, mr),
    ]
    write_table(args.output, args.keyword, xs, sigmas, "energy", "eV",
                args.yunits, args.extrap, header)


def cmd_csv(args):
    xs, sigmas = [], []
    for line in args.input:
        line = line.split("#")[0].strip()
        if not line:
            continue
        words = line.replace(",", " ").split()
        if len(words) < 2:
            sys.exit("error: expected two columns, got: %s" % line)
        xs.append(float(words[0]))
        sigmas.append(float(words[1]))

    if len(xs) < 2:
        sys.exit("error: need at least 2 data points")
    for i in range(1, len(xs)):
        if xs[i] <= xs[i - 1]:
            sys.exit("error: x values must increase monotonically "
                     "(row %d: %g <= %g)" % (i + 1, xs[i], xs[i - 1]))

    header = ["converted from %s by tools/tabulate_cross_section.py" %
              args.input.name]
    write_table(args.output, args.keyword, xs, sigmas, args.xvar, args.xunits,
                args.yunits, args.extrap, header)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd")
    sub.required = True

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--keyword", required=True,
                        help="section keyword to write into the table file")
    common.add_argument("--yunits", default="m^2", choices=sorted(YUNIT_SCALE),
                        help="cross section units to write (default m^2)")
    common.add_argument("--extrap", nargs=2, default=["constant", "constant"],
                        metavar=("LO", "HI"),
                        choices=["constant", "powerlaw", "vss", "error"],
                        help="extrapolation modes below/above the table range")
    common.add_argument("-o", "--output", type=argparse.FileType("w"),
                        default=sys.stdout, help="output file (default stdout)")

    p = sub.add_parser("vss", parents=[common],
                       help="tabulate the analytic VHS/VSS cross section")
    p.add_argument("--species", required=True, help="SPARTA species file")
    p.add_argument("--vss", required=True, help="SPARTA VSS parameter file")
    p.add_argument("--pair", nargs=2, required=True, metavar=("SP1", "SP2"))
    p.add_argument("--emin", type=float, default=1.0e-4,
                   help="lowest relative translational energy, eV")
    p.add_argument("--emax", type=float, default=1.0e3,
                   help="highest relative translational energy, eV")
    p.add_argument("-n", type=int, default=200, help="number of values")
    p.add_argument("--linear", action="store_true",
                   help="space values linearly instead of logarithmically")
    p.set_defaults(func=cmd_vss)

    p = sub.add_parser("csv", parents=[common],
                       help="convert a two-column (x,sigma) data file")
    p.add_argument("input", type=argparse.FileType("r"))
    p.add_argument("--xvar", default="energy", choices=["energy", "speed"])
    p.add_argument("--xunits", default="eV", choices=sorted(XUNIT_SCALE))
    p.set_defaults(func=cmd_csv)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
